### PR TITLE
Sec nav repertoire upcoming

### PR DESCRIPTION
**Pull request by burrozd**
Sec nav repertoire upcoming

### CODE REVIEW

**Review by KRQQN — CHANGES_REQUESTED** [review]
skall mergas till Sprint-1

**Comment by liber09** [comment]
Conflict needs to be resolved first

**Comment by liber09** [comment]
Approved your other PR but this now has conflicts because of that, needs to be resolved first

**Review by Rasmus3liasson — APPROVED** [review]
Merge conflict resolved hope it was correct or let me know

**Review by KRQQN — APPROVED** [review]

**Pull request merged**
