### PR TITLE
Replaced our temporary logotype

### LINKED ISSUE #25: Logotype

### PR DESCRIPTION
**Pull request by Rasmus3liasson**
Made a logotype that looks better then are previous one in my opinion.

Also change some href attribute so works on all html files.

### CODE REVIEW

**Comment by KRQQN** [comment]
många konflikter!

**Comment by Rasmus3liasson** [comment]
@Rkron91 vill tro att allt ska vara okej nu

**Comment by KRQQN** [comment]
> 

ser bra ut :)

**Review by KRQQN — APPROVED** [review]
Approvad :) 👍

**Pull request merged**
